version: '3.6'
services:
  ElasticSearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/logstash.conf/usr/share/logstash/config/logstash.conf:ro
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - ElasticSearch
    ports:
      - '5000:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xmx256m"
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - ElasticSearch
    networks:
      - elk

volumes:
  elastic_data: {}

networks:
  elk:
    name: elk

    